// app/api/search/route.js
import { query } from "../../../lib/db"; // keep relative unless @ alias is configured

const AMAZON_TAG = "tallzcanada-20";

function norm(v) {
  return (v || "").toString().trim().toLowerCase();
}

function amazonLink(asin) {
  return `https://www.amazon.ca/dp/${asin}?tag=${AMAZON_TAG}`;
}

/**
 * ✅ IMPORTANT:
 * Paste your FULL PRODUCTS array here exactly as it is in your local file,
 * so you keep every single item unchanged.
 *
 * I included what you pasted in chat, but your real file contains more items.
 */
const PRODUCTS = [
    {
    id: "PLTblzr1",
    asin: "PLTblzr1",
    title: "Tall Ecru Curved Hem Tailored Style Denim Blazer",
    title_fr: "Blazer style denim ajusté",
    brand: "PrettyLittleThing",
    store: "PrettyLittleThing.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/3/f/9/6/3f96e305228193a3d302f13f1897ea3df0b087b0_CNN2781_3_tall_ecru_curved_hem_tailored_style_denim_blazer.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-ecru-curved-hem-tailored-style-denim-blazer.html?_gl=1*1499zno*_up*MQ..*_ga*MTg2MzU1OTY0Ny4xNzY5MTg5MDA0*_ga_DQY8F6QKJ1*czE3NjkxODkwMDMkbzEkZzEkdDE3NjkxODkxMjIkajQkbDAkaDAkZFo1RTYzN1FxMGMyckxlcFZnd2lfWlR2LUFaWmJsOC1tcVE",
    source: "prettylittlething.ca",
  },
    {
    id: "pid=843284003",
    asin: "pid=843284003",
    title: "CashSoft Rib Midi Sweater Dress",
    title_fr: "Robe-chandail midi côtelée",
    brand: "Gap",
    store: "gapcanada.ca",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://www.gapcanada.ca/webcontent/0060/565/996/cn60565996.jpg",
    url: "https://www.gapcanada.ca/browse/product.do?pid=843284003&vid=2&pcid=13658&cid=13658&nav=meganav%3AFemme%3ACat%C3%A9gories%3ARobes#pdp-page-content",
    source: "gap",
  },
    {
    id: "ar77775",
    asin: "ar77775",
    title: "High-waisted wide-leg Japanese crepe trousers",
    title_fr: "Pantalon large taille haute en crêpe japonais",
    brand: "Aritzia",
    store: "aritiza.com",
    categories: ["pants", "workwear"],
    tall: true,
    image: "https://assets.aritzia.com/image/upload/c_crop,ar_1920:2623,g_south/q_auto,f_auto,dpr_auto,w_1200/s26_a06_95188_34050_off_a",
    url: "https://www.aritzia.com/en/product/the-effortless-pant%E2%84%A2/77775.html?color=34050_1",
    source: "aritzia",
  },
      {
    id: "PLTjj1",
    asin: "PLTjj1",
    title: "Tall vintage denim jacket",
    title_fr: "Veste en denim vintage",
    brand: "PrettyLittleThing",
    store: "PrettyLittleThing.ca",
    categories: ["tops"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/e/a/4/a/ea4ace34d8fa9274f28bbf50acaa2e0ced4a4ba2_CNN1945_2_tall_vintage_slim_fit_denim_jacket.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-vintage-slim-fit-denim-jacket.html?_gl=1*12zim35*_up*MQ..*_ga*NDE1ODkxMDkxLjE3NjkxODkzODc.*_ga_DQY8F6QKJ1*czE3NjkxODkzODckbzEkZzEkdDE3NjkxODkzODckajYwJGwwJGgwJGRFd2tOa2dsaWV2WVpJTEp3TzlueFpZY1dyTC11S29JZEtR",
    source: "prettylittlething.ca",
  },
  {
    id: "amz-B07B6GMPHC",
    asin: "B07B6GMPHC",
    title: "Lee Women's Regular Fit Bootcut Jeans",
    title_fr: "Jean évasé coupe régulière pour femmes Lee",
    brand: "Lee",
    store: "Amazon.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image:
      "https://m.media-amazon.com/images/I/61Fej2rPSwL._AC_SY445_SX342_QL70_ML2_.jpg",
    url: amazonLink("B07B6GMPHC"),
    source: "amazon",
  },
  {
    id: "amz-B0C7MYYS76",
    asin: "B0C7MYYS76",
    title: "Lee Women's Legendary Bootcut Jeans",
    title_fr: "Jean légendaire évasé pour femmes Lee",
    brand: "Lee",
    store: "Amazon.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/61QopScXiwL._AC_SY550_.jpg",
    url: amazonLink("B0C7MYYS76"),
    source: "amazon",
  },
  {
    id: "amz-B01EOX2G8C",
    asin: "B01EOX2G8C",
    title: "Lee Women's Modern Bootcut Jeans",
    title_fr: "Jean évasé moderne pour femmes Lee",
    brand: "Lee",
    store: "Amazon.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image:
      "https://m.media-amazon.com/images/I/81UkJtZLMvL._AC_SX342_SY445_QL70_ML2_.jpg",
    url: amazonLink("B01EOX2G8C"),
    source: "amazon",
  },
    {
    id: "PLTpts1",
    asin: "PLTpts1",
    title: "Tall black pinstripe wide leg pants",
    title_fr: "Pantalon large à rayures noires",
    brand: "PrettyLittleThing",
    store: "PrettyLittleThing.ca",
    categories: ["pants","workwear"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/5/9/8/5/598583463cf400cc1485e6e1087ee36dfbe9212f_CNK5078_2_tall_black_pinstripe_tailored_wide_leg_trousers.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-black-pinstripe-tailored-wide-leg-pants.html?_gl=1*1jcoy15*_up*MQ..*_ga*MTMxNzM3NzExMi4xNzY5MjE5NzMz*_ga_DQY8F6QKJ1*czE3NjkyMTk3MzMkbzEkZzEkdDE3NjkyMTk3MzMkajYwJGwwJGgwJGRodkd5TlJmc1czM2pTOC1yeTlsNVk4UlpOV3pHS19tV3J3",
    source: "prettylittlething.ca",
  },
    {
    id: "boohoo-HZZ38987",
    title: "Tall Snake Print Lace Trim Midaxi Dress",
    title_fr: "Robe mi-longue avec bordure en dentelle",
    brand: "Boohoo",
    store: "ca.boohoo.com",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://mediahub.boohoo.com/hzz38987_stone_xl/female-stone-tall-snake-print-lace-trim-midaxi-dress?w=675&fmt=auto&sm=C",
    url: "https://ca.boohoo.com/tall-snake-print-lace-trim-midaxi-dress/HZZ38987.html",
    source: "boohoo",
  },
  {
    id: "amz-B07CSM971H",
    asin: "B07CSM971H",
    title: "Lee Women's Secretly Shapes Straight Leg Jeans",
    title_fr: "Jean droit Secretly Shapes pour femmes Lee",
    brand: "Lee",
    store: "Amazon.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image:
      "https://m.media-amazon.com/images/I/710AvhgMtDL._AC_SX342_SY445_QL70_ML2_.jpg",
    url: amazonLink("B07CSM971H"),
    source: "amazon",
  },

  {
    id: "amz-B0FS7M9NZ1",
    asin: "B0FS7M9NZ1",
    title: "Crew Neck T-Shirt",
    title_fr: "T-shirt à col rond",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/61WUWYhoV3L._AC_SY550_.jpg",
    url: amazonLink("B0FS7M9NZ1"),
    source: "amazon",
  },
  {
    id: "PLTbls1",
    asin: "PLTbls1",
    title: "Tall charcoal pinstripe shirt",
    title_fr: "Chemise à rayures charbon",
    brand: "PrettyLittleThing",
    store: "PrettyLittleThing.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/6/0/7/d/607dbe42d3ab3202b5f149c11d64d9bcd6538ad2_CNP1759_2_tall_charcoal_pinstripe_oversized_shirt.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-charcoal-pinstripe-shirt.html?_gl=1*xb1x6c*_up*MQ..*_ga*MTI2ODM4MDYyMS4xNzY5MjE5ODQz*_ga_DQY8F6QKJ1*czE3NjkyMTk4NDMkbzEkZzEkdDE3NjkyMTk4NDMkajYwJGwwJGgwJGQ4RmpKTzg0UjBIUnZZYVNzYWJ5UmhIVnB3bm94T3Y5V0xn",
    source: "prettylittlething.ca",
  },
  {
    id: "amz-B0CRRG5D25",
    asin: "B0CRRG5D25",
    title: "Round Neck Buttoned T-Shirt",
    title_fr: "T-shirt boutonné à col rond",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops"],
    tall: true,
    image:
      "https://m.media-amazon.com/images/I/61ShURNh2YL._AC_SY445_SX342_QL70_ML2_.jpg",
    url: amazonLink("B0CRRG5D25"),
    source: "amazon",
  },
  {
    id: "amz-B0CY541HCX",
    asin: "B0CY541HCX",
    title: "Racerback Tops",
    title_fr: "Tops à dos nageur",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops","workout"],
    tall: true,
    image:
      "https://m.media-amazon.com/images/I/81tGYvEZaCL._AC_SX342_SY445_QL70_ML2_.jpg",
    url: amazonLink("B0CY541HCX"),
    source: "amazon",
  },
  {
    id: "amz-B0CJXV6N9Q",
    asin: "B0CJXV6N9Q",
    title: "Linen Short-Sleeve Buttoned Shirt",
    title_fr: "Chemise boutonnée en lin à manches courtes",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/7183tTld--L._AC_SX466_.jpg",
    url: amazonLink("B0CJXV6N9Q"),
    source: "amazon",
  },
  {
    id: "amz-B0CSMP6W73",
    asin: "B0CSMP6W73",
    title: "Striped Buttoned Shirt",
    title_fr: "Chemise rayée boutonnée",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/61aOjjSN36L._AC_SY679_.jpg",
    url: amazonLink("B0CSMP6W73"),
    source: "amazon",
  },
  {
    id: "amz-B07F23Y859",
    asin: "B07F23Y859",
    title: "Lightweight V-Neck Tunic",
    title_fr: "Tunique légère à col en V",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/81A1QQNPjkL._AC_SX569_.jpg",
    url: amazonLink("B07F23Y859"),
    source: "amazon",
  },
  {
    id: "amz-B0FCXTWGHR",
    asin: "B0FCXTWGHR",
    title: "Crewneck Raglan Tunic With Thumbholes",
    title_fr: "Tunique raglan à col rond avec trous pour les pouces",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71M2vcN6JPL._AC_SY741_.jpg",
    url: amazonLink("B0FCXTWGHR"),
    source: "amazon",
  },
      {
    id: "PLTdr1",
    asin: "PLTdr1",
    title: "Tall soft touch maxi dress",
    title_fr: "Robe maxi en tissu doux",
    brand: "PrettyLittleThing",
    store: "PrettyLittleThing.ca",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/a/f/f/5/aff5705616c599811430bb3e80da4f08243d25cd_CNM2882_3_tall_black_soft_touch_long_sleeve_maxi_dress.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-black-soft-touch-long-sleeve-maxi-dress.html?_gl=1*39wtmi*_up*MQ..*_ga*NDE1ODkxMDkxLjE3NjkxODkzODc.*_ga_DQY8F6QKJ1*czE3NjkxODkzODckbzEkZzEkdDE3NjkxODk0NzUkajYwJGwwJGgwJGRFd2tOa2dsaWV2WVpJTEp3TzlueFpZY1dyTC11S29JZEtR",
    source: "prettylittlething.ca",
  },
  {
    id: "amz-B0CF5DD9J6",
    asin: "B0CF5DD9J6",
    title: "Crewneck Pockets Tunic",
    title_fr: "Tunique à poches à col rond",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/715Q2OlaN9L._AC_SY606_.jpg",
    url: amazonLink("B0CF5DD9J6"),
    source: "amazon",
  },
  {
    id: "amz-B0BKXPLB26",
    asin: "B0BKXPLB26",
    title: "Crewneck Soft Sweatshirt",
    title_fr: "Chandail doux à col rond",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71eyp8Hz3jL._AC_SY500_.jpg",
    url: amazonLink("B0BKXPLB26"),
    source: "amazon",
  },
  {
    id: "amz-B0FVLWZ5PK",
    asin: "B0FVLWZ5PK",
    title: "V-Neck Sweater",
    title_fr: "Chandail à col en V",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71WlbIGW4cL._AC_SY741_.jpg",
    url: amazonLink("B0FVLWZ5PK"),
    source: "amazon",
  },
  {
    id: "amz-B0BJDGZHKL-pack",
    asin: "B0BJDGZHKL",
    title: "Tank Tops 3-Pack",
    title_fr: "Camisoles 3 pièces",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops","workout"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71PkY9YrOjL._AC_SX679_.jpg",
    url: amazonLink("B0BJDGZHKL"),
    source: "amazon",
  },
  {
    id: "amz-B0BJDGZHKL-stretch",
    asin: "B0BJDGZHKL",
    title: "Stretchy Tank Tops 3-Pack",
    title_fr: "Camisoles extensibles 3 pièces",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["tops","workout"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71RVqO23OPL._AC_SX679_.jpg",
    url: amazonLink("B0BJDGZHKL"),
    source: "amazon",
  },
  {
    id: "pcid=1367772560238",
    asin: "7772560238",
    title: "Lace-Trim V-Neck Crepe Maxi Dress",
    title_fr: "Robe maxi en crêpe à col en V avec dentelle",
    brand: "Gap",
    store: "gapcanada.ca",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://www.gapcanada.ca/webcontent/0060/139/746/cn60139746.jpg",
    url: "https://www.gapcanada.ca/browse/product.do?pid=777256023&vid=2&pcid=13658&cid=13658&nav=meganav%3AFemme%3ACat%C3%A9gories%3ARobes&locale=en_CA#pdp-page-content",
    source: "gap",
  },
  {
    id: "pid=875487013",
    asin: "875487013",
    title: "Poplin Cinched Midi Shirtdress",
    title_fr: "Robe chemise midi cintrée en popeline",
    brand: "Gap",
    store: "gapcanada.ca",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://www.gapcanada.ca/webcontent/0061/217/347/cn61217347.jpg",
    url: "https://www.gapcanada.ca/browse/product.do?pid=875487013&vid=2&pcid=13658&cid=13658&nav=meganav%3AFemme%3ACat%C3%A9gories%3ARobes#pdp-page-content",
    source: "gap",
  },
  {
    id: "pid=7435620333",
    asin: "743562033",
    title: "Cotton Poplin Tuxedo-Front Midi Dress",
    title_fr: "Robe midi en popeline de coton à devant tuxedo",
    brand: "Banana Republic",
    store: "bananarepublic.gapcanada.ca",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://bananarepublic.gapcanada.ca/webcontent/0060/015/025/cn60015025.jpg",
    url: "https://bananarepublic.gapcanada.ca/browse/product.do?pid=743562033&vid=2&pcid=69883&cid=69883#pdp-page-content",
    source: "bananarepublic",
  },
  {
    id: "pid=pid=817746013",
    asin: "817746013",
    title: "Stretch-Crepe Flutter-Sleeve Maxi Dress",
    title_fr:" Robe maxi à manches volantées en crêpe extensible",
    brand: "Banana Republic",
    store: "bananarepublic.gapcanada.ca",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://bananarepublic.gapcanada.ca/webcontent/0059/754/934/cn59754934.jpg",
    url: "https://bananarepublic.gapcanada.ca/browse/product.do?pid=817746013&vid=2&pcid=69883&cid=69883#pdp-page-content",
    source: "bananarepublic",
  },
  {
    id: "tall-washed-black-high-waist-turn-up-hem-barrel-style-jean",
    title: "Tall Washed Black High Waist Turn Up Hem Barrel Style Jean",
    title_fr: "Jean noir délavé taille haute",
    brand: "PrettyLittleThing",
    store: "prettylittlething.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/a/7/9/d/a79d3bbd03962e943edc93d1f67b3d57a832a0c6_CNL7130_1_tall_washed_black_high_waist_turn_up_hem_barrel_style_jean.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-washed-black-high-waist-turn-up-hem-barrel-style-jean.html",
    source: "prettylittlething",
  },
  {
    id: "tall-vintage-washed-mid-rise-wide-leg-jeans",
    title: "Tall Vintage Washed Mid Rise Wide Leg Jeans",
    title_fr: "Jean large taille mi-haute délavé vintage",
    brand: "PrettyLittleThing",
    store: "prettylittlething.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/e/a/3/f/ea3f887dfd4308acd0e68169f3efd7ca28f9c709_CNL4596_2_tall_vintage_washed_mid_rise_wide_leg_jeans.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-vintage-washed-mid-rise-wide-leg-jeans.html",
    source: "prettylittlething",
  },
  {
    id: "tall-stone-tie-waist-trench-coat",
    title: "Tall Stone Tie Waist Trench Coat",
    title_fr: "Trench-coat taille nouée",
    brand: "PrettyLittleThing",
    store: "prettylittlething.ca",
    categories: ["outdoors","coats"],
    tall: true,
    image: "https://cdn-img.prettylittlething.com/4/0/b/3/40b33a947b973657eeebc50952dfd8def78b7b6b_CNO3230_1_tall_stone_tie_waist_trench_coat.jpg?imwidth=600",
    url: "https://www.prettylittlething.ca/tall-stone-tie-waist-trench-coat.html",
    source: "prettylittlething",
  },
  {
    id: "boohoo-HZZ01421",
    title: "Tall Soft Knit Marl Oversized High Neck Jumper",
    title_fr: "Pull oversize à col montant",
    brand: "Boohoo",
    store: "ca.boohoo.com",
    categories: ["dresses","workwear"],
    tall: true,
    image: "https://mediahub.boohoo.com/hzz01421_grey_xl/female-grey-tall-soft-knit-marl-oversized-high-neck-jumper?w=675&fmt=auto&sm=",
    url: "https://ca.boohoo.com/tall-soft-knit-marl-oversized-high-neck-jumper/HZZ01421.html",
    source: "boohoo",
  },
  {
    id: "miik-christal-pull-on-pintuck-ankle-pant",
    title: "Christal pull-on pintuck ankle pant",
    title_fr: "Pantalon cheville à plis",
    brand: "Miik",
    store: "miik.ca",
    categories: ["bottoms","workwear"],
    tall: true,
    image: "https://www.miik.ca/cdn/shop/files/Christal-pull-on-pintuck-dress-pant-black-long-for-women.webp?v=1763670270&width=750",
    url: "https://www.miik.ca/collections/tall-friendly-bottoms/products/christal-pull-on-pintuck-dress-pant?variant=40309668446282",
    source: "miik",
  },
  {
    id: "lululemon-prod9410008",
    title: "lululemon Align™ High-Rise Pant 31",
    title_fr: "lululemon Legging taille haute 31",
    brand: "Lululemon",
    store: "shop.lululemon.com",
    categories: ["bottoms","workout"],
    tall: true,
    image: "https://images.lululemon.com/is/image/lululemon/LW5DQPT_063787_1?wid=1080&op_usm=0.5,2,10,0&fmt=webp&qlt=80,1&fit=constrain,0&op_sharpen=0&resMode=sharp2&iccEmbed=0&printRes=72",
    url: "https://shop.lululemon.com/en-ca/p/womens-leggings/Align-Pant-Tall/_/prod9410008?color=63787",
    source: "lululemon",
  },
  {
    id: "lululemon-prod11720572",
    title: "Swift Mid-Rise Wide-Leg Pant",
    title_fr: "Pantalon taille mi-haute à jambe large",
    brand: "Lululemon",
    store: "shop.lululemon.com",
    categories: ["bottoms","workout"],
    tall: true,
    image: "https://images.lululemon.com/is/image/lululemon/LW5GX2S_070108_1?wid=1080&op_usm=0.5,2,10,0&fmt=webp&qlt=80,1&fit=constrain,0&op_sharpen=0&resMode=sharp2&iccEmbed=0&printRes=72",
    url: "https://shop.lululemon.com/en-ca/p/women-pants/Swift-Wide-Leg-Mid-Rise-Pant-MD/_/prod11720572?color=70108",
    source: "lululemon",
  },
  {
    id: "pid=8287690033105",
    title: "Low Rise Long & Lean Jeans",
    title_fr: "Jean long à taille basse",
    brand: "Gap",
    store: "gapcanada.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image: "https://www.gapcanada.ca/webcontent/0061/135/714/cn61135714.jpg",
    url: "https://www.gapcanada.ca/browse/product.do?pid=828769003&vid=2&pcid=1026616&cid=1026616#pdp-page-content",
    source: "gap",
  },
    {
    id: "pid=815641003",
    title: "High Rise ’90s Slim Straight Jeans",
    title_fr: "Jean droit taille haute années 90",
    brand: "Gap",
    store: "gapcanada.ca",
    categories: ["bottoms","jeans"],
    tall: true,
    image: "https://www.gapcanada.ca/webcontent/0060/058/319/cn60058319.jpg",
    url: "https://www.gapcanada.ca/browse/product.do?pid=815641003&vid=2&pcid=1026616&cid=1026616#pdp-page-content",
    source: "gap",
  },
    {
    id: "pid=7980270131010",
    title: "High-Waisted Pixie Skinny Ankle Pants",
    title_fr: "Pantalon skinny cheville taille haute",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["bottoms","pants", "workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0060/191/413/cn60191413.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=7980270131010&vid=2&pcid=1185233&cid=1185233&nav=meganav%3AWomen%3A%3A#pdp-page-content",
    source: "oldnavy",
  },
    {
    id: "pid=868001003",
    title: "High-Waisted Taylor Trouser Wide-Leg Pants",
    title_fr: "Pantalon large taille haute",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["bottoms","pants", "workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0060/974/082/cn60974082.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=868001003&vid=2&pcid=1185233&cid=1185233&nav=meganav%3AWomen%3A%3A#pdp-page-content",
    source: "oldnavy",
  },
    {
    id: "pid=868068003",
    title: "High-Waisted Pixie Flare Pants",
    title_fr: "Pantalon évasé taille haute",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["bottoms","pants", "workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0060/985/632/cn60985632.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=868068003&vid=2&pcid=1185233&cid=1185233&nav=meganav%3AWomen%3A%3A#pdp-page-content",
    source: "oldnavy",
  },
      {
    id: "pid=798103003",
    title: "High-Waisted Billie Straight Ankle Trouser",
    title_fr: "Pantalon droit cheville taille haute",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["bottoms","pants", "workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0059/511/280/cn59511280.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=798103003&vid=1&pcid=1185233&cid=1185233&nav=meganav%3AWomen%3A%3A#pdp-page-content",
    source: "oldnavy",
  },
{
    id: "pid=798437003",
    title: "Oversized Button-Down Boyfriend Shirt",
    title_fr: "Chemise boyfriend oversize boutonnée",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0059/907/041/cn59907041.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=798437003&vid=2&pcid=1185233&cid=1185233#pdp-page-content",
    source: "oldnavy",
  },
{
    id: "pid=802090033",
    title: "Satin Button-Down Shirt",
    title_fr: "Chemise boutonnée en satin",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0060/447/361/cn60447361.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=802090033&vid=2&pcid=1185233&cid=1185233#pdp-page-content",
    source: "oldnavy",
  },
  {
    id: "pid=513768023",
    title: "Classic Button-Down Shirt",
    title_fr: "Chemise boutonnée classique",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0056/231/587/cn56231587.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=513768023&vid=2&pcid=1185233&cid=1185233#pdp-page-content",
    source: "oldnavy",
  },
    {
    id: "pid=861166003",
    title: "Garter-Knit Cardigan Sweater",
    title_fr: "Cardigan en tricot",
    brand: "Old Navy",
    store: "oldnavy.gapcanada.ca",
    categories: ["tops","workwear"],
    tall: true,
    image: "https://oldnavy.gapcanada.ca/webcontent/0060/803/584/cn60803584.jpg",
    url: "https://oldnavy.gapcanada.ca/browse/product.do?pid=861166003&vid=2&pcid=20408&cid=20408&nav=meganav%3AWomen%3AWomen%E2%80%99s+Tops%3ASweaters+%26+Cardigans#pdp-page-content",
    source: "oldnavy",
  },
    {
    id: "489933",
    title: "Straight-Leg High-Rise Plaid Pants - The Modern Stretch (R) - Tall",
    title_fr: "Pantalon taille haute jambe droite",
    brand: "Reitmans",
    store: "reitmans.com",
    categories: ["bottoms", "pants","workwear"],
    tall: true,
    image: "https://www.reitmans.com/on/demandware.static/-/Sites-Reitmans-catalog/default/dw626681be/images/xlarge/reitmans_489933_252_0.jpg",
    url: "https://www.reitmans.com/en/straight-leg-high-rise-plaid-pants---the-modern-stretch-%28r%29---tall/489933.html?dwvar_489933_color=Chestnut-&cgid=shop-by-fit-tall",
    source: "reitmans",
  },
      {
    id: "488882",
    title: "Tapered-Leg High-Rise Pants - The Modern Stretch (R) - Tall",
    title_fr: "Pantalon taille haute jambe fuselée",
    brand: "Reitmans",
    store: "reitmans.com",
    categories: ["bottoms", "pants","workwear"],
    tall: true,
    image: "https://www.reitmans.com/on/demandware.static/-/Sites-Reitmans-catalog/default/dw2407cc39/images/xlarge/reitmans_488882_1_0.jpg",
    url: "https://www.reitmans.com/en/tapered-leg-high-rise-pants---the-modern-stretch-%28r%29---tall/488882.html?dwvar_488882_color=Black&cgid=shop-by-fit-tall",
    source: "reitmans",
  },
        {
    id: "460407",
    title: "Straight-Leg High-Rise Pant - The Iconic (R) - Tall",
    title_fr: "Pantalon taille haute jambe droite",
    brand: "Reitmans",
    store: "reitmans.com",
    categories: ["bottoms", "pants","workwear"],
    tall: true,
    image: "https://www.reitmans.com/on/demandware.static/-/Sites-Reitmans-catalog/default/dw1759ab5e/images/xlarge/reitmans_460407_1_0.jpg",
    url: "https://www.reitmans.com/en/straight-leg-high-rise-pant---the-iconic-%28r%29---tall/460407.html?dwvar_460407_color=Black&cgid=shop-by-fit-tall",
    source: "reitmans",
  },
          {
    id: "492890",
    title: "Wide-Leg Mid-Rise Denim Trousers - Tall",
    title_fr: "Pantalon en denim taille mi-haute jambe large",
    brand: "Reitmans",
    store: "reitmans.com",
    categories: ["bottoms", "pants","workwear"],
    tall: true,
    image: "https://www.reitmans.com/on/demandware.static/-/Sites-Reitmans-catalog/default/dwf0428f3d/images/xlarge/reitmans_492890_497_0.jpg",
    url: "https://www.reitmans.com/en/wide-leg-mid-rise-denim-trousers---tall/492890.html?dwvar_492890_color=Rinse%20denim&cgid=shop-by-fit-tall",
    source: "reitmans",
  },
    {
    id: "amz-B07PPXFNFG",
    asin: "B07PPXFNFG",
    title: "Womens Belice Ballet Flat Ballet Flat",
    title_fr: "Ballerine pour femmes",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["shoes"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/61uXNShKvUL._AC_SX679_.jpg",
    url: amazonLink("B07PPXFNFG"),
    source: "amazon",
  },
   {
    id: "amz-B088KGMNMY",
    asin: "B088KGMNMY",
    title: "Womens Pointed-Toe Ballet Flat",
    title_fr: "Ballerine à bout pointu pour femmes",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["shoes"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/61pYRNE1DAL._AC_SX679_.jpg",
    url: amazonLink("B088KGMNMY"),
    source: "amazon",
  },
     {
    id: "amz-B0CLKM42S5",
    asin: "B0CLKM42S5",
    title: "Women's Flats Shoes",
    title_fr: "Chaussures plates pour femmes",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["shoes"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71pqDMh6nfL._AC_SY695_.jpg",
    url: amazonLink("B0CLKM42S5"),
    source: "amazon",
  },
  {
    id: "amz-B07PN6B2HJ",
    asin: "B07PN6B2HJ",
    title: "Womens Lace Up Combat Boot Combat Boot",
    title_fr: "Bottes de combat à lacets pour femmes",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["shoes"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71pZc39OtkL._AC_SX679_.jpg",
    url: amazonLink("B07PN6B2HJ"),
    source: "amazon",
  },
 {
    id: "amz-B0BXWJ3R6C",
    asin: "B0BXWJ3R6C",
    title: "Skechers Womens Go Walk Flex Slip-ins - Relish Sneaker",
    title_fr: "Baskets Skechers Go Walk Flex Slip-ins",
    brand: "Skechers",
    store: "Amazon.ca",
    categories: ["shoes","sneakers","workout"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/81ZPrRYUBML._AC_SX695_.jpg",
    url: amazonLink("B0BXWJ3R6C"),
    source: "amazon",
  },
{
    id: "amz-B0D9C6F412",
    asin: "B0D9C6F412",
    title: "Skechers Womens Bobs Squad Chaos Current Muse Sneaker",
    title_fr: "Baskets Skechers Bobs Squad Chaos Current Muse pour femmes",
    brand: "Skechers",
    store: "Amazon.ca",
    categories: ["shoes","sneakers","workout"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/81eMFpaRp6L._AC_SY675_.jpg",
    url: amazonLink("B0D9C6F412"),
    source: "amazon",
  },
  {
    id: "amz-B0CJT5FHSY",
    asin: "B0CJT5FHSY",
    title: "Under Armour Unisex-Adult Lockdown 7 Sneaker",
    title_fr: "Baskets Under Armour Lockdown 7 pour adultes unisexes",
    brand: "Under Armour",
    store: "Amazon.ca",
    categories: ["shoes","sneakers","workout"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/51DP1mh7mSL._AC_SY695_.jpg",
    url: amazonLink("B0CJT5FHSY"),
    source: "amazon",
  },
    {
    id: "amz-B0D9781JC9",
    asin: "B0D9781JC9",
    title: "HOBIBEAR Barefoot Minimalist Zero Drop Canvas Slip-on Shoes",
    title_fr: "Chaussures HOBIBEAR Barefoot Minimalist Zero Drop Canvas Slip-on",
    brand: "Amazon",
    store: "Amazon.ca",
    categories: ["shoes"],
    tall: true,
    image: "https://m.media-amazon.com/images/I/71fT-N8dAtL._AC_SY695_.jpg",
    url: amazonLink("B0D9781JC9"),
    source: "amazon",
  },
   {
    id: "606297",
    title: "Sam Edelman Loraine Loafer",
    title_fr: "Mocassin Loraine de Sam Edelman",
    brand: "Sam Edelman",
    store: "dsw.com",
    categories: ["shoes"],
    tall: true,
    image: "https://assets.designerbrands.com/match/Site_Name/606297_203_ss_01/?quality=85&io=transform:fit,width:1280",
    url: "https://www.dsw.com/product/sam-edelman-loraine-loafer/606297?activeColor=203",
    source: "dsw",
  },
{
    id: "600513",
    title: "Reebok Nano Court Training Shoe - Women's",
    title_fr: "Chaussure d'entraînement Reebok Nano Court pour femmes",
    brand: "Reebok",
    store: "dsw.com",
    categories: ["shoes","workout","sneakers"],
    tall: true,
    image: "https://assets.designerbrands.com/match/Site_Name/600513_030_ss_01/?quality=85&io=transform:fit,width:1280",
    url: "https://www.dsw.com/product/reebok-nano-court-training-shoe---womens/600513?activeColor=charcoalgrey_multicolor",
    source: "dsw",
  },

  // ✅ Paste the rest of your items below this line (from your local file)
];

export async function GET(request) {
  const { searchParams } = new URL(request.url);

  const rawCategory = norm(searchParams.get("category") || "all");
  const q = norm(searchParams.get("q") || "");

  // ✅ NEW: brands filter (comma-separated)
  const brandsRaw = searchParams.get("brands") || "";
  const brands = brandsRaw ? brandsRaw.split(",").map(norm).filter(Boolean) : [];

  const categoryAliases = {
    all: "all",
    top: "tops",
    tops: "tops",
    bottom: "bottoms",
    bottoms: "bottoms",
    workout: "workout",
  };
  const category = categoryAliases[rawCategory] || rawCategory || "all";

  const includeRatings =
    searchParams.get("includeRatings") === "1" ||
    searchParams.get("includeRatings") === "true";

  let filtered = PRODUCTS;

  // ✅ Category filter
  if (category && category !== "all") {
    filtered = filtered.filter((p) => {
      const cats = Array.isArray(p.categories) ? p.categories.map(norm) : [];
      return cats.includes(category);
    });
  }

  // ✅ Brand filter (multi-select)
  if (brands.length > 0) {
    filtered = filtered.filter((p) => brands.includes(norm(p.brand)));
  }

  // ✅ Keyword filter
  if (q) {
    filtered = filtered.filter((p) => {
      const cats = Array.isArray(p.categories) ? p.categories.join(" ") : "";
      const haystack = [p.title, p.brand, p.store, p.asin, p.source, cats]
        .map(norm)
        .join(" ");
      return haystack.includes(q);
    });
  }

  // If no ratings requested, return quickly (cacheable)
  if (!includeRatings || filtered.length === 0) {
    return Response.json(filtered, {
      headers: { "Cache-Control": "public, max-age=60, s-maxage=300" },
    });
  }

  // Attach ratings/count from DB in one query for all products
  try {
    const ids = filtered.map((p) => p.id);

    const agg = await query(
      `
      SELECT
        product_id,
        COALESCE(AVG(rating), 0) AS avg_rating,
        COUNT(*) AS count
      FROM product_reviews
      WHERE product_id = ANY($1)
      GROUP BY product_id
      `,
      [ids]
    );

    const stats = new Map(
      (agg.rows ?? []).map((r) => [
        r.product_id,
        {
          averageRating: Number(r.avg_rating ?? 0),
          reviewCount: Number(r.count ?? 0),
        },
      ])
    );

    const enriched = filtered.map((p) => {
      const s = stats.get(p.id) || { averageRating: 0, reviewCount: 0 };
      return { ...p, ...s };
    });

    return Response.json(enriched, {
      headers: { "Cache-Control": "no-store" },
    });
  } catch (err) {
    console.error("GET /api/search includeRatings error:", err);
    // If DB fails, still return products
    return Response.json(filtered, {
      headers: { "Cache-Control": "public, max-age=60, s-maxage=300" },
    });
  }
}
